// Canonical fallback content for the homepage magazine grid, used whenever
// Supabase returns fewer than 6 published articles. Keep this as the
// single source of truth for that dataset — see components/MagazineGrid.js.
export const FALLBACK_ARTICLES = [
  {
    id: "feat-1",
    slug: "fed-interest-rate-pivot-2026-strategy",
    title: "Federal Reserve Signals Key Rate Pivot: How to Position Your Portfolio Today",
    excerpt: "With inflation moderating and employment metrics shifting, Wall Street strategists outline top high-yield cash reserves, bond strategies, and stock allocations for 2026.",
    category: "Loans",
    read_time: "5 min read",
    created_at: "2026-08-19",
    author: "Elena Rostova",
    featured_image_url: "https://images.unsplash.com/photo-1590283603385-17ffb3a7f29f?q=80&w=1200&auto=format&fit=crop",
  },
  {
    id: "top-1",
    slug: "7-high-yield-savings-accounts-beating-inflation",
    title: "7 High-Yield Savings Accounts Currently Offering Over 5.2% APY",
    excerpt: "Maximize your emergency fund returns with FDIC-insured digital banks offering record yields.",
    category: "Savings",
    read_time: "3 min read",
    created_at: "2026-08-18",
    author: "Marcus Vance",
    featured_image_url: "https://images.unsplash.com/photo-1559526324-4b87b5e36e44?q=80&w=600&auto=format&fit=crop",
  },
  {
    id: "top-2",
    slug: "credit-score-hacks-boost-50-points-30-days",
    title: "3 Credit Score Hacks to Add 50 Points to Your FICO in 30 Days",
    excerpt: "Simple utilization strategies and reporting techniques mortgage lenders don't always advertise.",
    category: "Credit",
    read_time: "4 min read",
    created_at: "2026-08-17",
    author: "Sophia Chen",
    featured_image_url: "https://images.unsplash.com/photo-1563986768609-322da13575f3?q=80&w=600&auto=format&fit=crop",
  },
  {
    id: "trend-1",
    slug: "2026-tax-bracket-changes-wealth-preservation",
    title: "2026 Tax Bracket Adjustments: Crucial Deductions Every High Earner Must Lock In Now",
    category: "Taxes",
    read_time: "4 min read",
    created_at: "2026-08-19",
    reads: "14.2k",
  },
  {
    id: "lifestyle-fashion-1",
    slug: "luxury-capsule-wardrobe-staples-cost-per-wear",
    title: "10 Luxury Capsule Wardrobe Staples That Pay Off in Cost-Per-Wear",
    excerpt: "Investment-grade pieces that quietly outperform fast fashion on true cost-per-wear, from tailored blazers to timeless leather goods.",
    category: "Lifestyle",
    tags: ["Fashion", "Style"],
    read_time: "4 min read",
    created_at: "2026-08-19",
    reads: "9.8k",
    author: "Isabella Grant",
    featured_image_url: "https://images.unsplash.com/photo-1490481651871-ab68de25d43d?q=80&w=600&auto=format&fit=crop",
  },
  {
    id: "lifestyle-fitness-1",
    slug: "daily-longevity-energy-stack-high-performing-professionals",
    title: "The Daily Longevity & Energy Stack for High-Performing Professionals",
    excerpt: "The supplement, sleep, and movement stack top executives use to sustain energy and cognitive performance through demanding schedules.",
    category: "Lifestyle",
    tags: ["Wellness", "Fitness"],
    read_time: "5 min read",
    created_at: "2026-08-18",
    reads: "8.6k",
    author: "Dr. Marcus Reyes",
    featured_image_url: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?q=80&w=600&auto=format&fit=crop",
  },
];
